name: yannsadowskidev

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - html-output:/usr/share/nginx/html:ro

  webhook-listener:
    build:
      context: ./webhook-listener
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - REPO_URL=${REPO_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - html-output:/html-output
      - .:/project

  hugo-builder:
    build:
      context: ./hugo-builder
      args:
        REPO_URL: ${REPO_URL}
    environment:
      - REPO_URL=${REPO_URL}
    volumes:
      - html-output:/html-output
    profiles:
      - build

volumes:
  html-output:
